name: ChatOps Example

on:
  issue_comment: 
    types: [created]

jobs:
  build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Building the application..."
